version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    networks:
      - "mynet"

  database:
    platform: ""
    image: "mysql:latest"
    container_name: "db-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "privacy_policy_db"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - "./resources/db.sql:/docker-entrypoint-initdb.d/db.sql"
    networks:
      - "mynet"

networks:
  mynet:
    driver: "bridge"