name: Build

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build .

    - name: Run go vet
      run: go vet .

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck .


    #- name: Run tests
    #  run: go test -race -vet=off ./...

  deploy:

    runs-on: ubuntu-latest

    needs: [build] # Only run this workflow when "build" workflow succeeds
   # if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
    steps:
    - uses: actions/checkout@v2

    # Deploy to Docker registry
    - name: Deploy to Docker registry
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: doolaa/policygenerator
        tag_with_ref: true