name: Build

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build .

    - name: Run go vet
      run: go vet .

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck .


    #- name: Run tests
    #  run: go test -race -vet=off ./...

  push:

    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ needs.build.result == 'success' }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Grant execute permission to versioning script
        run: chmod +x versioning-script.sh
      
      - name: Generate Semantic Version
        id: version
        run: |
          echo "::set-output name=version::$(./versioning-script.sh)"  

      - name: Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: doolaa/policygenerator:${{ steps.version.outputs.version }}, doolaa/policygenerator:latest
          
